### ISSUE TITLE
Correlation Numbers for heatmap

### ISSUE THREAD

**Issue by abhaydhiman** [Ayush-Malik/basic_ML_model_building_assistant_for_regression_and_classification_problems#1]
The heatmap used for correlation is just a kind of graph and not showing any kind of correlation number for the features on the graph. For now, it just appears on the tooltip and its better to add the correlation number on the graph itself instead of showing the same on the tooltip.

___ 
![image](https://user-images.githubusercontent.com/45531376/90102869-2a53fb80-dd5f-11ea-8c41-07ad12dde29d.png)

**Comment by Aaditya1978** [comment]
Fixed by #2
